import os

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
MODELS_DIR = os.path.join(PROJECT_ROOT, "models")
DATA_DIR = os.path.join(PROJECT_ROOT, "data")

os.makedirs(MODELS_DIR, exist_ok=True)
os.makedirs(DATA_DIR, exist_ok=True)

NUM_SCENARIOS = 20
EPOCHS_PER_SCENARIO = 1800
BASE_LAT = 37.7749
BASE_LON = -122.4194
SAMPLE_RATE_HZ = 1

WINDOW_SIZE = 30
CN0_SIMILAR_THRESHOLD = 2.0
POSITION_JUMP_THRESHOLD_M = 100
ALTITUDE_JUMP_THRESHOLD_M = 50
CN0_STEP_THRESHOLD_DB = 6.0

TIME_SERIES_FEATURES = [
    "cn0_mean", "cn0_variance", "cn0_std", "cn0_spread",
    "num_sats", "speed_mps", "altitude", "hdop",
    "alt_diff", "speed_diff"
]

XGB_N_ESTIMATORS = 200
XGB_MAX_DEPTH = 6
XGB_LEARNING_RATE = 0.1
XGB_SUBSAMPLE = 0.8
XGB_COLSAMPLE = 0.8
XGB_SCALE_POS_WEIGHT = 1.5

DEEP_CONV1_FILTERS = 32
DEEP_CONV2_FILTERS = 64
DEEP_LSTM_HIDDEN = 64
DEEP_LSTM_LAYERS = 2
DEEP_DENSE_HIDDEN = 64
DEEP_DROPOUT = 0.3
DEEP_LEARNING_RATE = 1e-3
DEEP_WEIGHT_DECAY = 1e-4
DEEP_BATCH_SIZE = 64
DEEP_EPOCHS = 100
DEEP_PATIENCE = 15
DEEP_GRAD_CLIP = 1.0

SPOOF_SCORE_THRESHOLD = 0.5
CN0_VARIANCE_ALERT = 10.0
POSITION_DEVIATION_ALERT_M = 50.0

TEST_SIZE = 0.2
CV_FOLDS = 5
RANDOM_SEED = 42

LABEL_AUTHENTIC = 0
LABEL_SPOOFED = 1
LABEL_NAMES = ["Authentic", "Spoofed"]